In [25]:
import numpy as np

In [ ]:
#1_1

In [3]:
a = np.arange(0,20).reshape(4,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [4]:
a.shape

(4, 5)

In [5]:
a.ndim

2

In [7]:
a.size

20

In [8]:
a.itemsize

4

In [10]:
#1_2

In [11]:
b = np.arange(4).reshape(2,2)
b

array([[0, 1],
       [2, 3]])

In [13]:
b.dtype.name

'int32'

In [14]:
#1_3

In [15]:
c = np.ones((4,4))
c

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
d = np.random.randn(3,2)
d

array([[-1.32756935,  2.40293258],
       [-0.67777441,  1.48021704],
       [-1.09738378, -0.53387099]])

In [17]:
#1_4

In [18]:
n1 = np.arange(12).reshape(3,4)
n1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [19]:
nx = n1.shape[0]
ny = n1.shape[1]
i = j = 0
sumy = 0
while i < ny:
    while j < nx:
        sumy += n1[j][i]
        j += 1
    print("第",i,"列：",sumy)
    sumy = 0
    j = 0
    i += 1

第 0 列： 12
第 1 列： 15
第 2 列： 18
第 3 列： 21


In [20]:
nx = n1.shape[0]
i = 0
while i < nx:
    print("第",i,"行：",np.min(n1[i]))
    i += 1

第 0 行： 0
第 1 行： 4
第 2 行： 8


In [21]:
#1_5

In [26]:
n2 = np.random.randn(3)
n2

array([2.02265396, 0.84954399, 0.87002847])

In [27]:
np.sqrt(n2)

array([1.42220039, 0.9217071 , 0.93275317])

In [28]:
for i in n2:
    print(np.std(i))

0.0
0.0
0.0


In [29]:
#1_6

In [31]:
n3 = np.arange(9)
n3

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [32]:
np.square(n3)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64], dtype=int32)

In [33]:
n3[2]

2

In [34]:
n3[2:5]

array([2, 3, 4])

In [35]:
#1_7

In [36]:
n4 = np.random.randn(3,3)
n5 = np.random.randn(3,3)
print(n4)
print(n5)

[[-0.62199669  0.13776291 -0.16489279]
 [ 0.35825417 -1.26928101  1.70006753]
 [ 1.51446364 -0.36407005  0.12888774]]
[[ 0.23401421 -0.68524638 -0.56530165]
 [-0.27558245 -0.12588477 -0.67535538]
 [ 1.2232388   1.08623979  0.68117291]]


In [37]:
n6 = np.vstack((n4,n5))
n6

array([[-0.62199669,  0.13776291, -0.16489279],
       [ 0.35825417, -1.26928101,  1.70006753],
       [ 1.51446364, -0.36407005,  0.12888774],
       [ 0.23401421, -0.68524638, -0.56530165],
       [-0.27558245, -0.12588477, -0.67535538],
       [ 1.2232388 ,  1.08623979,  0.68117291]])

In [38]:
n7 = np.hstack((n4,n5))
n7

array([[-0.62199669,  0.13776291, -0.16489279,  0.23401421, -0.68524638,
        -0.56530165],
       [ 0.35825417, -1.26928101,  1.70006753, -0.27558245, -0.12588477,
        -0.67535538],
       [ 1.51446364, -0.36407005,  0.12888774,  1.2232388 ,  1.08623979,
         0.68117291]])

In [39]:
#1_8

In [40]:
z = np.zeros((2,3))
z

array([[0., 0., 0.],
       [0., 0., 0.]])

In [41]:
z[1][2] = 1
z

array([[0., 0., 0.],
       [0., 0., 1.]])

In [42]:
#1_9

In [43]:
z1 = np.diag((1,2,3,4))
z1

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [44]:
#1_10

In [45]:
z2 = np.arange(9).reshape(3,3)
z2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [46]:
z3 = np.random.randn(4,4)
z3

array([[-1.80892651,  0.36520744,  0.49463083, -1.11451447],
       [-1.30946807, -1.54668672,  1.01497273, -1.17632677],
       [-1.05570731,  2.71772327,  0.36220055,  0.1420171 ],
       [ 0.12916464, -1.31065604, -0.9247308 ,  1.79021682]])